global
	log 127.0.0.1	local0
	log 127.0.0.1	local1 notice
	#log loghost	local0 info
	maxconn 4096
	#chroot /usr/share/haproxy
#	user haproxy
#	group haproxy
	daemon
	#debug
	#quiet

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	retries	3
	option redispatch
	timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
# HAProxy 1.3 not keep alive support
#	option	httpclose
# HAProxy 1.4 keep alive supported
	timeout client  5000
	option http-server-close
	balance	roundrobin

frontend http *:80
	option	forwardfor except 192.168.2.2
	reqadd	X-Forwarded-Proto:\ http
	default_backend default_farm

frontend https 127.0.0.1:8443
	option	forwardfor except 127.0.0.1
	reqadd	X-Forwarded-Proto:\ https
	default_backend default_farm

## Special proxy for statistics
listen  stats 127.0.0.1:8543
        stats enable
 ## here you can define a custom url for the stats
        stats uri     /haproxy?stats
        stats realm   Haproxy\ Statistic
        stats auth     stat:demo
        option  forwardfor except 127.0.0.1
        server srv1 192.168.2.2:543 redir https://192.168.2.2:543/haproxy?stats

backend default_farm
        balance roundrobin
        reqadd  FRONT_END_COMPANY:\ default
        server  node_1 10.205.11.191:8080 check
        server  node_2 10.205.11.191:9090 check